import Head from 'next/head'
import { Inter } from '@next/font/google'
import Hero from '../components/Hero'
import Featured from '@/components/Featured'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>D1 Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} bg-base-100 sm:mt-[66px] mb-[64px] sm:mb-0`}>
        <Hero />
        <Featured />
      </main>
    </>
  )
}
